### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by pellem** [sidewinder94/LolAnimationChanger#1]
Salut,
Ton programme télécharge les animations que l'on souhaite... Qu'en est-il si je souhaite créer moi même une animation et la passer à ton programme ?
Quel type de fichier (extension, specificités ?), dois-je la placer dans un dossier spécial pour y avoir accès ?

Merci d'avance pour ta réponse,
Cordialement...

**Comment by sidewinder94** [comment]
Bonjour,

il y a effectivement possibilité d'appliquer des thèmes "inconnus".

Par contre aucune fonction pour automatiser le tout pour le moment (c'est prévu)

Pour cela il est nécessaire de créer un dossier (nom au choix, mais éviter les espaces, pas sur que le launcher supporte) dans :
`Riot Games\League of Legends\RADS\projects\lol_air_client\releases\<dernière_version>\deploy\mod\lgn\themes`

Dans ce dossier, il faudra respecter la structure suivante : 

```
loginCustom (le dossier crée juste avant)
  |- cs_bg_champions.png (image de fond quand l'animation est désactivé)
  |- login.swf (récupérable dans les autres thèmes 'exceptés les spéciaux type Sona DJ))
  |- flv
  |   |- login-loop.flv
  |   |- login-intro.flv (en principe le intro est joué avant le loop, puis le loop est joué en boucle)
  |- music
      |- LoginScreenLoop.mp3
      |- LoginScreenIntro.mp3 (même fonctionnement que précédemment)
```

Dans un futur proche, il sera possible de fournir un fichier zip en entrée.

Il devra contenir le dossier crée ci-dessus.

Et dans un futur un peu plus éloigné, je pense permettre l'ajout de nouvelles sources permettant de fournir les écrans de chargement (et un filtre sur la boite déroulante parce que la j'en suis a la soixantaine..... Et ça commence à faire beaucoup).

**Comment by sidewinder94** [comment]
Cela à t'il répondu a la question ? que je puisse fermer l'issue ?
